Oos 9 registratie keuze maken type aanmelding
ICTOOSDb1/KamerConnect pull request #11
Opened 2024-11-22 15:49 UTC by samberkhout

2024-11-23 09:06 UTC, Aernout5 reviewed
Ziet er goed uit

2024-11-23 09:25 UTC, Aernout5 commented on KamerConnect.View.MAUI/Pages/Registration.xaml
> +
nog wat witregels hier weghalen

2024-11-23 12:07 UTC, RenzeBoerman requested changes

2024-11-23 12:07 UTC, RenzeBoerman commented on KamerConnect.View.MAUI/Pages/Registration.xaml.cs
> +		if (SelectedTab == "searching house")
SelectedTab een enum maken?

2024-11-23 12:07 UTC, RenzeBoerman commented on KamerConnect.View.MAUI/Pages/Registration.xaml.cs
> +		SelectTab("searching house");
Deze functie is deels Nederlands die hieronder ook!

2024-11-25 17:57 UTC, RenzeBoerman approved these changes

2024-11-25 18:04 UTC, merged